name: seconds
description: Simple functions to work with seconds. Used for compact dateTime storage (e.g. in database, or JWT "iat" claim).
version: 1.0.6
author: Subbotin Aleksei <darkandjeweled@gmail.com>
homepage: https://github.com/Moonspeaker/seconds

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  datetime_utc_converter: ^1.0.1